//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model1", "BlogsPosts", "Blogs", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.Blogs), "Posts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.Posts), true)]

#endregion

namespace WebApplication1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Blogs> Blogs
        {
            get
            {
                if ((_Blogs == null))
                {
                    _Blogs = base.CreateObjectSet<Blogs>("Blogs");
                }
                return _Blogs;
            }
        }
        private ObjectSet<Blogs> _Blogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Posts> Posts
        {
            get
            {
                if ((_Posts == null))
                {
                    _Posts = base.CreateObjectSet<Posts>("Posts");
                }
                return _Posts;
            }
        }
        private ObjectSet<Posts> _Posts;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Blogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlogs(Blogs blogs)
        {
            base.AddObject("Blogs", blogs);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Posts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPosts(Posts posts)
        {
            base.AddObject("Posts", posts);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Blogs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Blogs : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Blogs object.
        /// </summary>
        /// <param name="blogId">Initial value of the BlogId property.</param>
        /// <param name="blogName">Initial value of the BlogName property.</param>
        public static Blogs CreateBlogs(global::System.Int32 blogId, global::System.String blogName)
        {
            Blogs blogs = new Blogs();
            blogs.BlogId = blogId;
            blogs.BlogName = blogName;
            return blogs;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlogId
        {
            get
            {
                return _BlogId;
            }
            set
            {
                if (_BlogId != value)
                {
                    OnBlogIdChanging(value);
                    ReportPropertyChanging("BlogId");
                    _BlogId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BlogId");
                    OnBlogIdChanged();
                }
            }
        }
        private global::System.Int32 _BlogId;
        partial void OnBlogIdChanging(global::System.Int32 value);
        partial void OnBlogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BlogName
        {
            get
            {
                return _BlogName;
            }
            set
            {
                OnBlogNameChanging(value);
                ReportPropertyChanging("BlogName");
                _BlogName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BlogName");
                OnBlogNameChanged();
            }
        }
        private global::System.String _BlogName;
        partial void OnBlogNameChanging(global::System.String value);
        partial void OnBlogNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "BlogsPosts", "Posts")]
        public EntityCollection<Posts> Posts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Posts>("Model1.BlogsPosts", "Posts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Posts>("Model1.BlogsPosts", "Posts", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Posts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Posts : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Posts object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="postName">Initial value of the PostName property.</param>
        /// <param name="blogsBlogId">Initial value of the BlogsBlogId property.</param>
        public static Posts CreatePosts(global::System.Int32 id, global::System.String postName, global::System.Int32 blogsBlogId)
        {
            Posts posts = new Posts();
            posts.Id = id;
            posts.PostName = postName;
            posts.BlogsBlogId = blogsBlogId;
            return posts;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PostName
        {
            get
            {
                return _PostName;
            }
            set
            {
                OnPostNameChanging(value);
                ReportPropertyChanging("PostName");
                _PostName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PostName");
                OnPostNameChanged();
            }
        }
        private global::System.String _PostName;
        partial void OnPostNameChanging(global::System.String value);
        partial void OnPostNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlogsBlogId
        {
            get
            {
                return _BlogsBlogId;
            }
            set
            {
                OnBlogsBlogIdChanging(value);
                ReportPropertyChanging("BlogsBlogId");
                _BlogsBlogId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BlogsBlogId");
                OnBlogsBlogIdChanged();
            }
        }
        private global::System.Int32 _BlogsBlogId;
        partial void OnBlogsBlogIdChanging(global::System.Int32 value);
        partial void OnBlogsBlogIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "BlogsPosts", "Blogs")]
        public Blogs Blog
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Blogs>("Model1.BlogsPosts", "Blogs").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Blogs>("Model1.BlogsPosts", "Blogs").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Blogs> BlogReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Blogs>("Model1.BlogsPosts", "Blogs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Blogs>("Model1.BlogsPosts", "Blogs", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
