//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model1", "TeacherStudent", "Teacher", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(datalayer.Teacher), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(datalayer.Student), true)]

#endregion

namespace datalayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student> Students
        {
            get
            {
                if ((_Students == null))
                {
                    _Students = base.CreateObjectSet<Student>("Students");
                }
                return _Students;
            }
        }
        private ObjectSet<Student> _Students;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Teacher> Teachers
        {
            get
            {
                if ((_Teachers == null))
                {
                    _Teachers = base.CreateObjectSet<Teacher>("Teachers");
                }
                return _Teachers;
            }
        }
        private ObjectSet<Teacher> _Teachers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Teachers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTeachers(Teacher teacher)
        {
            base.AddObject("Teachers", teacher);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sAge">Initial value of the SAge property.</param>
        /// <param name="sAddress">Initial value of the SAddress property.</param>
        /// <param name="teacherTID">Initial value of the TeacherTID property.</param>
        public static Student CreateStudent(global::System.Int32 id, global::System.String sAge, global::System.String sAddress, global::System.Int32 teacherTID)
        {
            Student student = new Student();
            student.Id = id;
            student.SAge = sAge;
            student.SAddress = sAddress;
            student.TeacherTID = teacherTID;
            return student;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SName
        {
            get
            {
                return _SName;
            }
            set
            {
                OnSNameChanging(value);
                ReportPropertyChanging("SName");
                _SName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SName");
                OnSNameChanged();
            }
        }
        private global::System.String _SName;
        partial void OnSNameChanging(global::System.String value);
        partial void OnSNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SAge
        {
            get
            {
                return _SAge;
            }
            set
            {
                OnSAgeChanging(value);
                ReportPropertyChanging("SAge");
                _SAge = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SAge");
                OnSAgeChanged();
            }
        }
        private global::System.String _SAge;
        partial void OnSAgeChanging(global::System.String value);
        partial void OnSAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SAddress
        {
            get
            {
                return _SAddress;
            }
            set
            {
                OnSAddressChanging(value);
                ReportPropertyChanging("SAddress");
                _SAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SAddress");
                OnSAddressChanged();
            }
        }
        private global::System.String _SAddress;
        partial void OnSAddressChanging(global::System.String value);
        partial void OnSAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeacherTID
        {
            get
            {
                return _TeacherTID;
            }
            set
            {
                OnTeacherTIDChanging(value);
                ReportPropertyChanging("TeacherTID");
                _TeacherTID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TeacherTID");
                OnTeacherTIDChanged();
            }
        }
        private global::System.Int32 _TeacherTID;
        partial void OnTeacherTIDChanging(global::System.Int32 value);
        partial void OnTeacherTIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "TeacherStudent", "Teacher")]
        public Teacher Teacher
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("Model1.TeacherStudent", "Teacher").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("Model1.TeacherStudent", "Teacher").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Teacher> TeacherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("Model1.TeacherStudent", "Teacher");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Teacher>("Model1.TeacherStudent", "Teacher", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Teacher")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Teacher : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Teacher object.
        /// </summary>
        /// <param name="tID">Initial value of the TID property.</param>
        /// <param name="tName">Initial value of the TName property.</param>
        /// <param name="tCourse">Initial value of the TCourse property.</param>
        public static Teacher CreateTeacher(global::System.Int32 tID, global::System.String tName, global::System.String tCourse)
        {
            Teacher teacher = new Teacher();
            teacher.TID = tID;
            teacher.TName = tName;
            teacher.TCourse = tCourse;
            return teacher;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TID
        {
            get
            {
                return _TID;
            }
            set
            {
                if (_TID != value)
                {
                    OnTIDChanging(value);
                    ReportPropertyChanging("TID");
                    _TID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TID");
                    OnTIDChanged();
                }
            }
        }
        private global::System.Int32 _TID;
        partial void OnTIDChanging(global::System.Int32 value);
        partial void OnTIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TName
        {
            get
            {
                return _TName;
            }
            set
            {
                OnTNameChanging(value);
                ReportPropertyChanging("TName");
                _TName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TName");
                OnTNameChanged();
            }
        }
        private global::System.String _TName;
        partial void OnTNameChanging(global::System.String value);
        partial void OnTNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TCourse
        {
            get
            {
                return _TCourse;
            }
            set
            {
                OnTCourseChanging(value);
                ReportPropertyChanging("TCourse");
                _TCourse = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TCourse");
                OnTCourseChanged();
            }
        }
        private global::System.String _TCourse;
        partial void OnTCourseChanging(global::System.String value);
        partial void OnTCourseChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "TeacherStudent", "Student")]
        public EntityCollection<Student> NavigationProperty1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("Model1.TeacherStudent", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("Model1.TeacherStudent", "Student", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "TeacherStudent", "Student")]
        public EntityCollection<Student> Students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("Model1.TeacherStudent", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("Model1.TeacherStudent", "Student", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
